### ISSUE TITLE
get LngLat in map

### ISSUE THREAD

**Issue by akenore** [Simon-the-Shark/django-mapbox-location-field#21]
hi,
i have use json_serializer = serializers.get_serializer("json")()
to get LngLat in javascript of the map to show marker on map but i have this error after i add a variable 
to the code 
Uncaught Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, an object {lon: <lng>, lat: <lat>}, or an array of [<lng>, <lat>]
because we can't have the longitude and latitude separated we get it like that (12.550343, 55.665957)
so in the Mapbox don't work do you have a possibility to separate what is in database like lng =  12.550343 and lat = 55.665957
that it can work in map
this is the code that I use to show in map
<script>
                           
                            var LngLat = '{{ partie.terrain }}';
							var map = new mapboxgl.Map({
							container: 'map',
							style: 'mapbox://styles/mapbox/satellite-streets-v11',
							center: [12.550343, 55.665957],
							zoom: 18
							});
							
							console.log(LongLat);
                            var marker = new mapboxgl.Marker()
                                .setLngLat(LongLat)
                                .addTo(map);
                        </script>

**Comment by Simon-the-Shark** [comment]
Hi! I'll contact you after the weekend

**Comment by Simon-the-Shark** [comment]
I suppose you're using [the plain LocationField](https://github.com/Simon-the-Shark/django-mapbox-location-field#plain-database)

**Comment by Simon-the-Shark** [comment]
In this case, the python representation of coordinates is a [tuple](https://www.w3schools.com/python/python_tuples.asp)

**Comment by Simon-the-Shark** [comment]
And Mapbox's requires [javascript's array](https://www.w3schools.com/js/js_arrays.asp), which has identical syntax as [Python's list](https://www.w3schools.com/python/python_lists.asp)

**Comment by Simon-the-Shark** [comment]
I suppose you're using [the plain LocationField](https://github.com/Simon-the-Shark/django-mapbox-location-field#plain-database)

In this case, the python representation of coordinates is a [tuple](https://www.w3schools.com/python/python_tuples.asp)

And Mapbox's requires [javascript's array](https://www.w3schools.com/js/js_arrays.asp), which has identical syntax as [Python's list](https://www.w3schools.com/python/python_lists.asp)

And the transformation from a tuple to a list is quite simple. For example, you can create a simple template filter (or tag if you prefer).

In order to do it, just create in your app folder `templatetags`, which contains empty `__init__.py` file and your `custom_filters.py`. And then paste there below simple code:
```python
from django import template

register = template.Library()

@register.filter
def tuple_to_array(tuple):
    return list(tuple)
```

And then in your HTML template: 
* load your filters with:
  ```Django  
  {% load custom_filters %}
  ```
* and use it like this:
  ```{{ object.location | tuple_to_array}}```
  (replace `object.location` with your name. I suppose `partie.terrain` in your example)
For example your previous example would look like:
  ```Django
  {% load custom_filters %}
  <script> 
  var LngLat = {{ partie.terrain | tuple_to_array }}; 
  var map = new mapboxgl.Map({ container: 'map', style: 'mapbox://styles/mapbox/satellite-streets-v11', center: [12.550343, 55.665957], zoom: 18 }); 
  console.log(LongLat); 
  var marker = new mapboxgl.Marker() .setLngLat(LongLat) .addTo(map); 
  </script>
  ```

You can read more on custom template tags and filters on [official documentation](https://docs.djangoproject.com/en/3.1/howto/custom-template-tags/)

**Comment by Simon-the-Shark** [comment]
Also, thanks for drawing my attention to this. I'm going to introduce such filter in the next version of my package to makes this operation even simpler. I'll let you know once it's released

**Comment by akenore** [comment]
thank's a lot it was helpful you do a great job

**Comment by Simon-the-Shark** [comment]
There's a new release [`v1.6.4`](https://github.com/Simon-the-Shark/django-mapbox-location-field/releases/tag/v1.6.4) which includes this filter. Feel free to contact me in case of further troubles with my package.
