### ISSUE TITLE
Minor Improvements

### ISSUE THREAD

**Issue by urzbs** [simon-the-shark/django-mapbox-location-field#30]
Hey,
<ol>
<li>
I noticed that the result for LocationField is (Long, Lat) instead of conventional (Lat, Long) - Is there any reason for this?<br/>
When people use this value and post it to google its always on the reverse of the world because its mixed up. <br/>
<a href="https://en.wikipedia.org/wiki/ISO_6709">ISO 6709 - Latitude comes before longitude</a>

</li>
<br/>
<li>
Is it possible to specify the size of the white Address Search Field inside the Location Picker Widget? <br/> 
A lot of Addresses are Cut Off with (...) because their Address is longer. I think it could improve user experience when you dont need to scroll inside the field to double check Addresses

</li>
</ol>

All the best!

**Comment by reustle** [comment]
Hey, I'm not at all involved with this project (yet) but would like to give some feedback.

Regarding point 1, I believe it's because this is a mapbox specific library, and this is the order that mapbox uses officially. https://docs.mapbox.com/help/glossary/lat-lon/

> For instance, Mapbox GL JS and most Mapbox web services APIs use the format `longitude,latitude`

As for the size of the location field, I'm sure there's so me way to hack it using css or js, if there is no clean way to modify the size through this library.

**Comment by simon-the-shark** [comment]
Regarding the coordinates order, it's explained in README:
 https://github.com/simon-the-shark/django-mapbox-location-field#versions-140

quoting:

Since version 1.4.0 the order of coordinates convention has been changed. Now the order is longitude, latitude. This change has been caused by support for spatial databases. Nevertheless, more user-friendly is order latitude, longitude(Google Maps uses it). That's why coordinates are falsely swapped in frontend and then after POST request in form field are swapped back into longitude, latitude order and saved to database.
My conclusion is that the location is falsely swapped in frontend and if you create location without our custom form field or just operate on a raw model in the backend, you will have to use the longitude, latitude order.
Versions before 1.4.0 always uses latitude, longitude order.

**Comment by simon-the-shark** [comment]
And when it comes to the size of the address field, web technologies have the advantage that you can always override the original CSS of any container. So, setting the size in your CSS files is pretty simple. Just like that:
` .mapboxgl-ctrl-geocoder {
max-width: unset;
width: 1000px;
}`

Read more about css's 'width' property here: https://www.w3schools.com/cssref/pr_dim_width.asp

**Comment by simon-the-shark** [comment]
If anyone would like to contribute and build Django implementation that overrides it for the coder, I'd be happy to review and merge, but personally don't have time right now.
